var videoPlaylist = [
	{ id: 'Onet82xMWdg', start: 4334, end: 4772, title: 'Reid+Wolken+Kelly - (Live at The Anteroom)Juju', artist: '', genre: '' },
	{ id: '6sB8vvA_6rQ', start: 1, end: 1593, title: 'Bo and The Constrictors - Lobofest 21 ', artist: '', genre: '' },
	{ id: 'OGuTg98uTjg', start: 1, end: 1426, title: 'Te Kahui — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 254, end: 645, title: 'FOTA - Ashton', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 23172, end: 23513, title: 'TOUGH GUY - Last One', artist: '', genre: '' },
	{ id: 'y3-LF-9y1Vw', start: 1, end: 238, title: 'Kylie Price - Not Lost', artist: '', genre: '' },
	{ id: 'AFYyCTUdDuQ', start: 133, end: 1017, title: 'DJ Shan - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 448, end: 575, title: 'RYECHI -  TERRESTRIAL', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 791, end: 1128, title: 'FILTH WIZARD - Phillips Head', artist: '', genre: '' },
	{ id: 'wIlck2PsFVM', start: 1, end: 1970, title: 'Local Elementz & Roarz - ŌHHH22 ', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 16644, end: 19755, title: 'LOOM - Space Concert', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 1560, end: 1877, title: 'FOTA - Wake up', artist: '', genre: '' },
	{ id: 'HkFe1prlhmA', start: 1, end: 482, title: 'Cypher Session - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'yMalm0erWto', start: 2110, end: 2370, title: 'ROSA BLACK & PAUL ALLEN - A Night for Nick Knox', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 434, end: 663, title: 'KOMMI - Whakakapia', artist: '', genre: '' },
	{ id: '1uKp4Tems4M', start: 814, end: 1008, title: 'Person Will - Rays', artist: '', genre: '' },
	{ id: 'IQGXKkpUz4A', start: 276, end: 2074, title: 'SWINGBRIDGE - Howl at the moon', artist: '', genre: '' },
	{ id: 'hx_zXAC0cSU', start: 1, end: 171, title: 'Common Ground Crew - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'colqm8kF16o', start: 589, end: 960, title: 'Step', artist: '', genre: '' },
	{ id: 'wVFA4gm0K8Q', start: 1, end: 1536, title: 'Ollie & The Crooks - Lobofest 21 ', artist: '', genre: '' },
	{ id: '4SbVszlEw3Y', start: 1, end: 1773, title: 'King Homeboy - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'O6e3xm1P3gc', start: 394, end: 700, title: 'Cash Guitar - Christmas Time ', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 20040, end: 23475, title: 'SOMATECH - Space Concert', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 1699, end: 1883, title: 'KOMMI - Oka', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 955, end: 1144, title: 'RYECHI -  DIGGIN (GOLDMINES)', artist: '', genre: '' },
	{ id: 'colqm8kF16o', start: 3, end: 363, title: 'Stomp', artist: '', genre: '' },
	{ id: 'y3-LF-9y1Vw', start: 805, end: 1288, title: 'Kylie Price - Searching for a Saint', artist: '', genre: '' },
	{ id: 'PlNc_NrxXS0', start: 1, end: 1552, title: 'Yayné - ŌHHH24 [FULL SET] #vibes', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 645, end: 1094, title: 'FOTA - 4 walls', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 2340, end: 2502, title: 'KOMMI - Ai Ana Kai Horetātā', artist: '', genre: '' },
	{ id: 'IQGXKkpUz4A', start: 1, end: 1302, title: ' ', artist: '', genre: '' },
	{ id: 't3S_1owNgg0', start: 1, end: 1386, title: 'Tali Joy - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'SLsg2lt_wC8', start: 1010, end: 2340, title: 'House of 2000 - Evo', artist: '', genre: '' },
	{ id: 'dx1OdF7DkyM', start: 1, end: 1262, title: 'The Horse - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'YqwxL_QmpyA', start: 1, end: 1368, title: 'Glad Rabbit - Lobofest 21 ', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 2138, end: 2340, title: 'KOMMI - Takataka', artist: '', genre: '' },
	{ id: 'X1-uLV4BgHU', start: 1, end: 1517, title: 'Bulletproof Convertible - Lobofest 21 ', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 1369, end: 1560, title: 'FOTA - Bed', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 1, end: 205, title: 'KOMMI - Soundscape (Karakia)', artist: '', genre: '' },
	{ id: 'GoP7KiDgCkg', start: 1, end: 1971, title: 'Dudstown Soundsystem - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'Onet82xMWdg', start: 2383, end: 3256, title: 'Reid+Wolken+Kelly - (Live at The Anteroom) Lonely Woman', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 581, end: 800, title: 'House of 2000 - Big Decks', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 1, end: 254, title: 'FOTA - White lies', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 1263, end: 1699, title: 'KOMMI - Tāiro', artist: '', genre: '' },
	{ id: 'wMKOGZy4MmA', start: 4982, end: 7193, title: 'DLOW (1/2)  - NEON EXsPOSURE', artist: '', genre: '' },
	{ id: 'xX6NIpgr8WA', start: 1, end: 990, title: 'Thanks - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 0, end: 96, title: 'Alcatraz - intro', artist: '', genre: '' },
	{ id: 'SLsg2lt_wC8', start: 200, end: 545, title: 'Hystera - Hystera - sONG 2', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 1883, end: 2138, title: 'KOMMI - Taipō', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 575, end: 684, title: 'RYECHI -  ALL OF THE MONEY PT.1', artist: '', genre: '' },
	{ id: 'DBf3rH0QIyo', start: 1993, end: 2220, title: 'Unrested stops (2022 11 01)', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 1, end: 1281, title: 'MadNeTeX — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 1807, end: 1897, title: 'House of 2000 - Tech Scratch (outro)', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 286, end: 1807, title: 'Alcatraz - Out on the hustle', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 18183, end: 19138, title: 'MAN RAY - MFP2', artist: '', genre: '' },
	{ id: 'yMalm0erWto', start: 2540, end: 2870, title: 'BROKEN HEARTBREAKERS - A Night for Nick Knox', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 674, end: 831, title: 'MadNeTeX — Ninja window', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 2358, end: 2681, title: 'FILTH WIZARD - Red Eve', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 1, end: 204, title: 'House of 2000 - Come on slots', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 10610, end: 12530, title: 'HASZARI - Space Concert', artist: '', genre: '' },
	{ id: 'TXrevEe3yAA', start: 1807, end: 1897, title: 'House of 2000 - Tech Scratch (outro)', artist: '', genre: '' },
	{ id: 'O6e3xm1P3gc', start: 0, end: 394, title: 'Cash Guitar - Hocus Pocus', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 906, end: 1046, title: 'KOMMI - Huri Te Whenua', artist: '', genre: '' },
	{ id: 'uhFob1qiNio', start: 2724, end: 3178, title: 'EXPJ - Trapse', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 535, end: 674, title: 'MadNeTeX — Domination', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 204, end: 424, title: 'House of 2000 - Chicks want to hit the beach', artist: '', genre: '' },
	{ id: 'Onet82xMWdg', start: 1027, end: 1505, title: 'Reid+Wolken+Kelly - (Live at The Anteroom) Requiet', artist: '', genre: '' },
	{ id: 'SLsg2lt_wC8', start: 567, end: 605, title: 'Hystera - Hystera - sONG 3', artist: '', genre: '' },
	{ id: '7XTt8SivXyA', start: 1, end: 1982, title: 'Benchmark Entertainment — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 1945, end: 2684, title: 'BETSY & THE RECKLESS - Space Concert', artist: '', genre: '' },
	{ id: 'Onet82xMWdg', start: 1505, end: 2074, title: 'Reid+Wolken+Kelly - (Live at The Anteroom) Lazy', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 1081, end: 1281, title: 'MadNeTeX —Gholden Ghost', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 3092, end: 3451, title: 'FOTA - Believe', artist: '', genre: '' },
	{ id: 'alOiYGYrCes', start: 1, end: 2954, title: 'Jay Knight (DJ set) - ŌHHH24', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 800, end: 1010, title: 'House of 2000 - Pussy in the Club', artist: '', genre: '' },
	{ id: '1uKp4Tems4M', start: 1302, end: 1588, title: 'Person Will - Podium', artist: '', genre: '' },
	{ id: 'colqm8kF16o', start: 363, end: 589, title: 'Surge', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 663, end: 906, title: 'KOMMI - Hōhā Nei Au', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 1, end: 359, title: 'FILTH WIZARD - Chimney Ethics', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 410, end: 584, title: 'Alcatraz - Chivalrys dead', artist: '', genre: '' },
	{ id: 'Q4ggmJTPSsI', start: 1, end: 1194, title: 'Ryechi - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 1046, end: 1263, title: 'KOMMI - Rere', artist: '', genre: '' },
	{ id: 'nmoTBVEOmPQ', start: 1, end: 942, title: 'Christian Tucker - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 286, end: 410, title: 'Alcatraz - Out on the hustle', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 1542, end: 1807, title: 'House of 2000 - Like a Man (Remix)', artist: '', genre: '' },
	{ id: 'O6e3xm1P3gc', start: 1, end: 1778, title: 'Cash Guitar - live at Pearl Diver ', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 831, end: 942, title: 'MadNeTeX —Frontline', artist: '', genre: '' },
	{ id: 'Yc2LRN-s8Kg', start: 1, end: 1051, title: 'One Day Sane - Lobofest 21 ', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 2960, end: 4851, title: 'Brendan Christie - Space Concert', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 1128, end: 1520, title: 'FILTH WIZARD - Tuskrider ', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 12900, end: 16065, title: '0DC - Space Concert', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 22536, end: 22811, title: 'TOUGH GUY - 18 Months', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 0, end: 204, title: 'Alcatraz - intro', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 1, end: 855, title: 'KĀHU - MFP 2 ', artist: '', genre: '' },
	{ id: '-ZsnEJllT5Y', start: 1, end: 174, title: 'Rye Chi (ft. Ridge Jaggers) - To Pastures (Music for People) ', artist: '', genre: '' },
	{ id: '1uKp4Tems4M', start: 514, end: 814, title: 'Person Will - The City', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 359, end: 791, title: 'FILTH WIZARD - Pliers ', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 312, end: 448, title: 'RYECHI -  MULL IT UP', artist: '', genre: '' },
	{ id: '7HxENNQql38', start: 8640, end: 10225, title: 'BLUES PROFESSOR - Space Concert', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 584, end: 788, title: 'Alcatraz - Shook ones freestyle', artist: '', genre: '' },
	{ id: 'QyXhMzLURKk', start: 1, end: 1267, title: 'Fre3dom - Lobofest 21 ', artist: '', genre: '' },
	{ id: 'tXkxqN3y4IM', start: 1, end: 925, title: 'RASA #1 - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'y3-LF-9y1Vw', start: 1055, end: 1299, title: 'Kylie Price - Keep On', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 148, end: 280, title: 'MadNeTeX — Blufyre', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 22268, end: 22536, title: 'TOUGH GUY - Believe it', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 1169, end: 1342, title: 'House of 2000 - Deep in the Club', artist: '', genre: '' },
	{ id: 'Q8BTkUb93uc', start: 1, end: 1225, title: 'MIC SURE Ft. Assorted Hamish — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'yMalm0erWto', start: 5979, end: 6233, title: 'MICHAEL MORRIS - A Night for Nick Knox', artist: '', genre: '' },
	{ id: 'Np8OjWImk2E', start: 1, end: 1418, title: 'Foul Play Syndicate — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 1094, end: 1369, title: 'FOTA - Phase', artist: '', genre: '' },
	{ id: 'y4jkCeM_hDo', start: 1, end: 287, title: 'Rezzy Crooks - Swimming Pools (Cover)(Music for People) ', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 1943, end: 2358, title: 'FILTH WIZARD - Captain Aᵇ ', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 280, end: 405, title: 'MadNeTeX — Separate', artist: '', genre: '' },
	{ id: 'Y1HIFa3CNNI', start: 1542, end: 1806, title: 'House of 2000 - Like a Man (Remix)', artist: '', genre: '' },
	{ id: '5TtnJgGc_yE', start: 1, end: 1112, title: 'Ridge Jaggers (DJ set) - ŌHHH24', artist: '', genre: '' },
	{ id: '9PJUYLaJftE', start: 1, end: 1267, title: 'Kritikal Analysis — ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 684, end: 955, title: 'RYECHI -  RESPITE', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 1, end: 2681, title: 'FILTH WIZARD - live at The Crown, Dunedin ', artist: '', genre: '' },
	{ id: 'XvE0GewwNlI', start: 7312, end: 8152, title: 'ABBY FLEUR - MUSIC FOR PEOPLE: 2 ', artist: '', genre: '' },
	{ id: 'wMKOGZy4MmA', start: 7518, end: 8900, title: 'DLOW (2/2) - NEON EXsPOSURE ', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 2288, end: 2578, title: 'FOTA - Sunny afternoon', artist: '', genre: '' },
	{ id: 'jlc8yAsk2O0', start: 1, end: 579, title: 'RASA #3 - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'yMalm0erWto', start: 4896, end: 5525, title: 'CALLA - A Night for Nick Knox', artist: '', genre: '' },
	{ id: 'XqleQ6NP9oM', start: 800, end: 1046, title: 'House of 2000 - Pussy in the Club', artist: '', genre: '' },
	{ id: 't3BjeWZtcdg', start: 1, end: 248, title: 'The Rhododendrons - The Apple ', artist: '', genre: '' },
	{ id: '7yn0uq2h3_0', start: 1, end: 1812, title: 'Ridge Jaggers - BootyBass GhettoTech (live) ', artist: '', genre: '' },
	{ id: 'j0xmcfdur6s', start: 1, end: 1670, title: 'PHX & Foul Play Syndicate - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'yMalm0erWto', start: 1585, end: 1810, title: 'ABBY FLEUR - A Night for Nick Knox', artist: '', genre: '' },
	{ id: 'XNdZ249SJlU', start: 2578, end: 3092, title: 'FOTA - Little green friend', artist: '', genre: '' },
	{ id: 'd1XTFC4_x2U', start: 1, end: 1531, title: 'Roarz & Infectiouss - ŌHHH24 [FULL SET] #rap', artist: '', genre: '' },
	{ id: 'Yvk_m9dpG2g', start: 1, end: 713, title: 'RASA #2 - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'rbDQt34jI7c', start: 1, end: 3156, title: 'Levine Lale (DJ set) - ŌHHH24 ', artist: '', genre: '' },
	{ id: 'Onet82xMWdg', start: 3691, end: 4334, title: 'Reid+Wolken+Kelly - (Live at The Anteroom) Sea Lady', artist: '', genre: '' },
	{ id: 'f8fhAe6YrTw', start: 1, end: 1696, title: 'Ferdishenko - WMFLive ', artist: '', genre: '' },
	{ id: 'gxxH73S1sac', start: 942, end: 1081, title: 'MadNeTeX —Swords over war', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 204, end: 312, title: 'RYECHI -  GWOP', artist: '', genre: '' },
	{ id: 'Onet82xMWdg', start: 5010, end: 5552, title: 'Reid+Wolken+Kelly - (Live at The Anteroom) Squally', artist: '', genre: '' },
	{ id: 'AJ99tU3lqzQ', start: 1, end: 933, title: '187 NESIANS FT. AFU — ŌHHH24 [FULL SET] #vibes', artist: '', genre: '' },
	{ id: 'ClngWDLgls4', start: 1010, end: 1169, title: 'House of 2000 - Evo', artist: '', genre: '' },
	{ id: '6TmjOxhDWps', start: 1, end: 1101, title: 'ZExII - ŌHHH22 ', artist: '', genre: '' },
	{ id: '6bk7ezTvfNs', start: 1, end: 943, title: 'ALXG - ŌHHH22 ', artist: '', genre: '' },
	{ id: 'SLsg2lt_wC8', start: 1, end: 153, title: 'Hystera - sONG 1', artist: '', genre: '' },
	{ id: 'x4ihJ5iqSHY', start: 20, end: 204, title: 'RYECHI -  TO PASTURES', artist: '', genre: '' },
	{ id: 'wjsr8ZmaRVA', start: 1520, end: 1943, title: 'FILTH WIZARD - Teeth', artist: '', genre: '' },
	{ id: 'oNo0vlT0UUQ', start: 96, end: 286, title: 'Alcatraz - to good freestyle', artist: '', genre: '' },

// Total: 145 tracks, 29:56:29
];
